# Generated by Django 2.2.1 on 2019-09-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculos',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
