# Generated by Django 2.2.1 on 2019-09-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0002_auto_20190918_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculos',
            old_name='preço',
            new_name='preco',
        ),
    ]
