# Generated by Django 2.2.1 on 2019-09-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0004_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='veicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='veicles.Veiculos', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='veicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veicles.Veiculos', verbose_name='imagens do veiculo'),
        ),
    ]
