# Generated by Django 2.2.1 on 2019-09-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0005_auto_20190920_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
