# Generated by Django 2.2.1 on 2019-09-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0006_auto_20190923_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='veicles/media'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='veicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='veicles.Veiculos', verbose_name='imagens do veiculo'),
        ),
    ]
