# Generated by Django 2.2.1 on 2019-09-26 08:42

from django.db import migrations, models
import django.db.models.deletion
import veicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0007_auto_20190926_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to=veicles.models.get_image_filename, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='veicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='veicles.Veiculos', verbose_name='imagens do veiculo'),
        ),
    ]
