# Generated by Django 2.2.1 on 2019-10-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0008_auto_20190926_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
