# Generated by Django 2.2.1 on 2019-10-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0009_auto_20191002_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to='get_image_filename', verbose_name='image'),
        ),
    ]
