# Generated by Django 2.2.1 on 2019-10-02 11:44

from django.db import migrations, models
import veicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0010_auto_20191002_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to=veicles.models.get_image_filename, verbose_name='image'),
        ),
    ]
