# Generated by Django 2.2.6 on 2019-10-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0012_auto_20191002_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='category',
            field=models.ManyToManyField(to='veicles.Categorias'),
        ),
    ]
