# Generated by Django 2.2.6 on 2019-10-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0013_veiculos_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='veicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='veicles.Veiculos'),
        ),
    ]
