# Generated by Django 2.2.6 on 2019-10-21 07:24

from django.db import migrations, models
import veicles.models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0014_auto_20191021_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(upload_to=veicles.models.get_image_filename),
        ),
    ]
