# Generated by Django 2.2.6 on 2019-11-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0015_auto_20191021_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='veicle',
        ),
    ]
