# Generated by Django 2.2.6 on 2019-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veicles', '0017_auto_20191121_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='first_gallery',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='mini_gallery',
            field=models.BooleanField(null=True),
        ),
    ]
