# Generated by Django 3.0 on 2020-06-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_produto_quantidade'),
        ('cart', '0004_auto_20200616_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='products.Produto'),
        ),
    ]
