# Generated by Django 3.0 on 2020-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200616_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='items',
            field=models.ManyToManyField(related_name='order', to='cart.Item'),
        ),
    ]
