# Generated by Django 2.2.1 on 2019-09-08 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MP4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('artista', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=350)),
                ('preview', models.TextField(max_length=200)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('code', models.TextField(max_length=2000)),
                ('idioma', models.CharField(choices=[('ENG', 'INGLES'), ('PT', 'PORTUGUES'), ('QQ', 'QUALQUER')], default='QQ', max_length=3)),
            ],
        ),
    ]
