# Generated by Django 2.2.1 on 2019-09-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='artista',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='mp4',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mp4',
            name='preço',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mp4',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
