# Generated by Django 2.2.1 on 2019-09-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0002_auto_20190909_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp4',
            name='preço',
        ),
    ]
