# Generated by Django 3.0 on 2020-06-02 19:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Inicial', 'Inicial'), ('Mini', 'Mini'), ('Promocao', 'Promocao'), ('Adjacentes', 'Adjacentes')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('CAMISA', 'CAMISA'), ('REGATA', 'REGATA'), ('VESTIDO', 'VESTIDO'), ('MACACAO', 'MACACAO'), ('CALSA', 'CALSA'), ('SHORT', 'SHORT'), ('INTIMA', 'INTIMA')], max_length=7)),
                ('publico', models.CharField(choices=[('Crianca', 'Crianca'), ('Adulto', 'Adulto')], max_length=7)),
                ('sexo', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=9)),
                ('idade_min', models.IntegerField(blank=True, choices=[(0, 0), ('Adulto', 'Adulto'), (1, 1), ('Adulto', 'Adulto'), (2, 2), ('Adulto', 'Adulto'), (3, 3), ('Adulto', 'Adulto'), (4, 4), ('Adulto', 'Adulto'), (5, 5), ('Adulto', 'Adulto'), (6, 6), ('Adulto', 'Adulto'), (7, 7), ('Adulto', 'Adulto'), (8, 8), ('Adulto', 'Adulto'), (9, 9), ('Adulto', 'Adulto'), (10, 10), ('Adulto', 'Adulto'), (11, 11), ('Adulto', 'Adulto')], default=0, null=True)),
                ('tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod', to='products.Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.get_image_filename)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=products.models.get_banner_image_filename)),
                ('link', models.URLField(default='products/home')),
                ('bannering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='products.Banner')),
            ],
        ),
    ]
