# Generated by Django 3.0 on 2020-03-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200323_0159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagem',
        ),
    ]
