# Generated by Django 3.0 on 2020-06-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
