# Generated by Django 3.0 on 2020-03-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200323_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='adulto',
        ),
        migrations.RemoveField(
            model_name='modelo',
            name='criança',
        ),
        migrations.AddField(
            model_name='modelo',
            name='publico',
            field=models.IntegerField(choices=[(1, 'Infantil'), (2, 'Adulto')], default=2),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='idade_min',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)]),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='sexo',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], max_length=9),
        ),
    ]
