# Generated by Django 3.0 on 2020-03-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200323_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='publico',
            field=models.IntegerField(choices=[('Crianca', 'Crianca'), ('Adulto', 'Adulto')], default=2),
        ),
    ]
