# Generated by Django 3.0 on 2020-03-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200323_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='idade_min',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0),
        ),
    ]
