# Generated by Django 3.0 on 2020-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200323_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='first_gallery',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
