# Generated by Django 3.0 on 2020-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_produto_first_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='mini_gallery',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
