# Generated by Django 3.0 on 2020-03-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200326_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Produto'),
        ),
    ]
