# Generated by Django 3.0 on 2020-03-27 03:58

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200327_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Inicial', 'Inicial'), ('Mini', 'Mini'), ('Promocao', 'Promocao'), ('Adjacentes', 'Adjacentes')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=products.models.get_banner_image_filename)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='products.Banner')),
            ],
        ),
    ]
