# Generated by Django 3.0 on 2020-03-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_banner_bannerimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerimages',
            old_name='banner',
            new_name='bannering',
        ),
    ]
