# Generated by Django 2.2.1 on 2019-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
                ('serial', models.DecimalField(decimal_places=3, max_digits=5)),
                ('topico', models.CharField(max_length=300)),
                ('avaible_days', models.DurationField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
