# Generated by Django 2.2.1 on 2019-09-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herewego', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do',
            name='status2',
        ),
    ]
