# Generated by Django 3.0 on 2020-02-26 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True, max_length=500)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('telefone', phone_field.models.PhoneField(default='21968151502', max_length=12)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True, max_length=400)),
                ('responsavel', models.CharField(max_length=100)),
                ('tel', phone_field.models.PhoneField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=services.models.get_image_filename)),
                ('servicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.Servicos')),
            ],
        ),
    ]
