# Generated by Django 3.0 on 2020-02-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200227_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servi', to='services.Parceiros'),
        ),
    ]
