# Generated by Django 3.0 on 2020-02-27 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20200227_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='telefone',
            field=phone_field.models.PhoneField(default='968151502', max_length=12),
        ),
    ]
