# Generated by Django 2.2.1 on 2019-09-04 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('c2vconfig', '0001_initial'), ('c2vconfig', '0002_auto_20190603_2147'), ('c2vconfig', '0003_auto_20190606_0956'), ('c2vconfig', '0004_auto_20190618_0246'), ('c2vconfig', '0005_tutorial'), ('c2vconfig', '0006_auto_20190624_0441'), ('c2vconfig', '0007_auto_20190708_0335'), ('c2vconfig', '0008_auto_20190904_1714'), ('c2vconfig', '0009_auto_20190904_1733')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MP4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('artista', models.CharField(default='Unknown', max_length=100)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=350)),
                ('preview', models.TextField(max_length=200)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('code', models.TextField(max_length=2000)),
                ('idioma', models.CharField(choices=[('ENG', 'INGLES'), ('PT', 'PORTUGUES'), ('QQ', 'QUALQUER')], default='QQ', max_length=3)),
                ('status1', models.CharField(choices=[('', ''), ('ONGOING', 'ONGOING'), ('LEARN', 'LEARN')], default='LEARN', max_length=8, null=True)),
                ('status2', models.BooleanField(choices=[('', ''), ('ONGOING', 'ONGOING'), ('LEARN', 'LEARN')], default='')),
            ],
        ),
    ]
