# Generated by Django 2.2.1 on 2019-06-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp4',
            name='artista',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mp4',
            name='url',
            field=models.URLField(default='unknow', max_length=300),
            preserve_default=False,
        ),
    ]
