# Generated by Django 2.2.1 on 2019-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0002_auto_20190603_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='artista',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
