# Generated by Django 2.2.1 on 2019-06-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0003_auto_20190606_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='imagem',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
