# Generated by Django 2.2.1 on 2019-06-24 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0004_auto_20190618_0246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=350)),
                ('preview', models.TextField(max_length=200)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('entendido', models.TextField(max_length=300)),
                ('idioma', models.CharField(choices=[('ENG', 'INGLES'), ('PT', 'PORTUGUES'), ('QQ', 'QUALQUER')], default='QQ', max_length=3)),
            ],
        ),
    ]
