# Generated by Django 2.2.1 on 2019-09-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0007_auto_20190708_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
