# Generated by Django 2.2.1 on 2019-09-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0008_auto_20190904_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='status1',
            field=models.CharField(choices=[('', ''), ('ONGOING', 'ONGOING'), ('LEARN', 'LEARN')], default='LEARN', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='status2',
            field=models.BooleanField(choices=[('', ''), ('ONGOING', 'ONGOING'), ('LEARN', 'LEARN')], default=''),
        ),
    ]
