# Generated by Django 2.2.1 on 2019-09-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c2vconfig', '0009_auto_20190904_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='status2',
        ),
    ]
