# Generated by Django 3.0 on 2020-02-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20200219_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='servicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.Servicos'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='parceiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servi', to='services.Parceiros'),
        ),
    ]
