# Generated by Django 2.2.1 on 2019-09-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('how', models.TextField(max_length=600)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status1', models.CharField(choices=[('OG', 'ONGOING'), ('LN', 'LEARN')], default='LN', max_length=2)),
            ],
        ),
    ]
