# Generated by Django 3.0 on 2020-02-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_sell_create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_product_sell', models.CharField(max_length=120)),
                ('product_price_sell', models.DecimalField(decimal_places=2, max_digits=500)),
                ('product_volume_sell', models.DecimalField(decimal_places=2, max_digits=500)),
                ('product_location_sell', models.CharField(max_length=120)),
                ('product_description_sell', models.TextField()),
            ],
        ),
    ]
