# Generated by Django 2.2.1 on 2019-06-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20190520_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço',
            new_name='preco',
        ),
    ]
