# Generated by Django 2.2.1 on 2019-09-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_year_in_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=3)),
                ('imagens', models.ImageField(blank=True, upload_to='')),
                ('urgencia', models.CharField(choices=[('5', 'MUITO_IMPORTANTE'), ('4', 'IMPORTANTE'), ('3', 'SUAVE'), ('2', 'RELAXA'), ('1', 'PRA DEPOIS')], max_length=40)),
            ],
        ),
    ]
