# Generated by Django 2.2.1 on 2019-09-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.CharField(max_length=200)),
                ('estoque', models.IntegerField(blank=True)),
                ('em_falta', models.BooleanField(blank=True)),
                ('categorias', models.ManyToManyField(to='produtos.Categoria')),
            ],
        ),
    ]
