# Generated by Django 3.0 on 2020-02-01 08:34

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField(blank=True, max_length=400)),
                ('responsavel', models.CharField(max_length=100)),
                ('tel', phone_field.models.PhoneField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True, max_length=500)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('telefone', phone_field.models.PhoneField(default='21968151502', max_length=11)),
                ('parceiros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Parceiros')),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to=services.models.get_image_filename)),
                ('servicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Servicos')),
            ],
        ),
    ]
