# Generated by Django 3.0 on 2020-02-01 08:59

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200201_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='tel',
            field=phone_field.models.PhoneField(max_length=12),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='telefone',
            field=phone_field.models.PhoneField(default='21968151502', max_length=12),
        ),
    ]
